module.exports = {
    ANSI_FG_YELLOWGREEN: (text) => `[2;32m${text}[0m`,
    ANSI_FG_GOLD: (text) => `[2;33m${text}[0m`,
    ANSI_FG_BLUE: (text) => `[2;34m${text}[0m`,
    ANSI_FG_PINK: (text) => `[2;35m${text}[0m`,
    ANSI_CHECKMARK: '[2;36m✓[0m',
    ANSI_X: '[2;33m[2;31mx[0m',
    ANSI_DASH: '[2;33m[0m[2;33m-[0m',
    ANSI_TEXT: (text) => `\n\`\`\`ansi\n${text}\`\`\``,
    LEADERBOARD_PAGE_UNDEFINED: 'There is nothing on this page.',
    LEADERBOARD_PAGE_HEADER: (page) => `**Page ${page}**\n\n`,
    GLOBAL_LEADERBOARD_EMPTY: 'There are no users on the leaderboard.',
    GLOBAL_LEADERBOARD_ENTRY: (n, userId, points, solved, record) => `**${n}.** <@${userId}>: ${points} pts, ${solved} solve(s)\nRecord: \` ${record}\`\n`,
    PROBLEM_LEADERBOARD_EMPTY: 'Nobody has solved this problem yet.',
    PROBLEM_LEADERBOARD_ENTRY: (n, userId, day, time, points) => `**${n}**. Solved by <@${userId}> on ${day} at ${time}\n`,
    LEADERBOARD_CONTINUED: (n) => `...${n} more`,
    WRITER_ADDED: (userId) => `Successfully made <@${userId}> a problem writer!`,
    WRITER_REMOVED: (userId) => `Successfully removed <@${userId}> from problem writers!`,
    PERMISSION_DENIED: 'You do not have permission to use this command.',
    PROBLEM_ADDED: 'Successfully added problem!',
    PROBLEM_EXISTS: 'Problem already exists.',
    PROBLEM_REMOVED: 'Successfully removed problem!',
    PROBLEM_NOT_FOUND: 'Problem does not exist.',
    RELEASE_CHANNEL_SET: 'Successfully set release channel!',
    SOLVE_INCORRECT: (attempts) => `Incorrect answer. You have tried ${attempts} time(s)`,
    SOLVE_CORRECT: `Correct answer!`,
    ALREADY_SOLVED: 'Correct answer! However, you earned no points because you have already solved this problem.',
    VIEWED_SOLUTION: 'Correct answer! However, you earned no points because you have viewed the solution or hint.',
    PROBLEM_EXPIRED: 'Correct answer! However, you earned no points because the problem no longer accepts answers.',
    SUBSCRIBED: 'You are now subscribed.',
    UNSUBSCRIBED: 'You are now unsubscribed.',
    HINT_UNAVAILABLE: 'Problem has no hint.',
    HINT: (hint) => `${hint}`,
    SOLUTION: (solution) => `${solution}`,
    PROBLEM_POINTS: (problemNumber, points) => `Problem ${problemNumber} is currently worth ${points} points`,
    NO_EXPIRATION: 'Always accepts answers',
    EXPIRATION_DATE: (day, time) => `Accepts answers until ${day} at ${time}`,
    LEAVING_SERVER: 'Leaving server...'
}