module.exports = {
    GLOBAL_LEADERBOARD_EMPTY: 'There are no users on the leaderboard.',
    GLOBAL_LEADERBOARD_ENTRY: (n, userId, points, solved) => `${n}. <@${userId}> has ${points} points with ${solved} problem(s) solved\n`,
    PROBLEM_LEADERBOARD_EMPTY: 'Nobody has solved this problem yet.',
    PROBLEM_LEADERBOARD_ENTRY: (n, userId, day, time) => `${n}. Solved by <@${userId}> on ${day} at ${time}\n`,
    LEADERBOARD_CONTINUED: (n) => `...${n} more`,
    WRITER_ADDED: (userId) => `Successfully made <@${userId}> a problem writer!`,
    WRITER_REMOVED: (userId) => `Successfully removed <@${userId}> from problem writers!`,
    PERMISSION_DENIED: 'You do not have permission to use this command.',
    PROBLEM_ADDED: 'Successfully added problem!',
    PROBLEM_EXISTS: 'Problem already exists.',
    PROBLEM_REMOVED: 'Successfully removed problem!',
    PROBLEM_NOT_FOUND: 'Problem does not exist.',
    RELEASE_CHANNEL_SET: 'Successfully set release channel!',
    SOLVE_INCORRECT: 'Incorrect answer.',
    SOLVE_CORRECT: (points) => `Correct answer! You earned ${points} points!`,
    ALREADY_SOLVED: 'Correct answer! However, you earned no points because you have already solved this problem.',
    VIEWED_SOLUTION: 'Correct answer! However, you earned no points because you have viewed the solution or hint.',
    PROBLEM_EXPIRED: 'Correct answer! However, you earned no points because the problem no longer accepts answers.',
    SUBSCRIBED: 'You are now subscribed.',
    UNSUBSCRIBED: 'You are now unsubscribed.',
    HINT_UNAVAILABLE: 'Problem has no hint.',
    HINT: (hint) => `${hint}`,
    SOLUTION: (solution) => `${solution}`,
    NO_EXPIRATION: 'Always accepts answers',
    EXPIRATION_DATE: (day, time) => `Accepts answers until ${day} at ${time}`,
}